// oauth.go — repositories for the OAuth2 server tables.
//
// Refresh-token rotation note: every successful refresh produces a new
// access_token AND a new refresh_token, marking the old one replaced=1.
// If a refresh token marked replaced=1 is presented again — that's a
// re-use, which under RFC 9700 §4.14.2 indicates the token has been
// stolen. We respond by revoking every token in the same chain
// (parent_token_id traversal). RevokeChain() implements that walk.
package repository

import (
	"database/sql"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
)

// ─── Clients ──────────────────────────────────────────────────────────────

type OAuthClient struct {
	ID                string `json:"id"`
	ClientID          string `json:"clientId"`
	ClientSecretHash  string `json:"-"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	HomepageURL       string `json:"homepageUrl"`
	LogoURL           string `json:"logoUrl"`
	MinLevel          int    `json:"minLevel"`
	RedirectURIs      string `json:"redirectUris"` // JSON array
	Scopes            string `json:"scopes"`       // JSON array
	Status            string `json:"status"`
	CreatedAt         string `json:"createdAt"`
	UpdatedAt         string `json:"updatedAt"`
}

type OAuthClientRepo struct{ db *sql.DB }

func NewOAuthClientRepo(db *sql.DB) *OAuthClientRepo { return &OAuthClientRepo{db: db} }

const oauthClientCols = `id, client_id, client_secret_hash, name, description,
                          homepage_url, logo_url, min_level, redirect_uris,
                          scopes, status, created_at, updated_at`

func scanOAuthClient(row interface{ Scan(dest ...any) error }) (*OAuthClient, error) {
	var c OAuthClient
	if err := row.Scan(&c.ID, &c.ClientID, &c.ClientSecretHash, &c.Name,
		&c.Description, &c.HomepageURL, &c.LogoURL, &c.MinLevel,
		&c.RedirectURIs, &c.Scopes, &c.Status, &c.CreatedAt, &c.UpdatedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	return &c, nil
}

func (r *OAuthClientRepo) FindByID(id string) (*OAuthClient, error) {
	row := r.db.QueryRow(`SELECT `+oauthClientCols+` FROM oauth_clients WHERE id = ?`, id)
	return scanOAuthClient(row)
}

func (r *OAuthClientRepo) FindByClientID(clientID string) (*OAuthClient, error) {
	row := r.db.QueryRow(`SELECT `+oauthClientCols+` FROM oauth_clients WHERE client_id = ?`, clientID)
	return scanOAuthClient(row)
}

func (r *OAuthClientRepo) List() ([]OAuthClient, error) {
	rows, err := r.db.Query(`SELECT ` + oauthClientCols + ` FROM oauth_clients ORDER BY created_at DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []OAuthClient
	for rows.Next() {
		c, err := scanOAuthClient(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *c)
	}
	return out, rows.Err()
}

type OAuthClientInput struct {
	ClientID         string
	ClientSecretHash string
	Name             string
	Description      string
	HomepageURL      string
	LogoURL          string
	MinLevel         int
	RedirectURIs     string
	Scopes           string
	Status           string
}

func (r *OAuthClientRepo) Create(in OAuthClientInput) (*OAuthClient, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	id := uuid.NewString()
	if in.Status == "" {
		in.Status = "active"
	}
	if in.RedirectURIs == "" {
		in.RedirectURIs = "[]"
	}
	if in.Scopes == "" {
		in.Scopes = "[]"
	}
	_, err := r.db.Exec(`
		INSERT INTO oauth_clients (id, client_id, client_secret_hash, name,
		    description, homepage_url, logo_url, min_level, redirect_uris,
		    scopes, status, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		id, in.ClientID, in.ClientSecretHash, in.Name, in.Description,
		in.HomepageURL, in.LogoURL, in.MinLevel, in.RedirectURIs,
		in.Scopes, in.Status, now, now)
	if err != nil {
		return nil, err
	}
	return r.FindByID(id)
}

// Update mutates everything except client_id (immutable) and the secret
// hash (a separate Rotate path).
func (r *OAuthClientRepo) Update(id string, in OAuthClientInput) (*OAuthClient, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	res, err := r.db.Exec(`
		UPDATE oauth_clients SET name = ?, description = ?, homepage_url = ?,
		    logo_url = ?, min_level = ?, redirect_uris = ?, scopes = ?,
		    status = ?, updated_at = ?
		WHERE id = ?`,
		in.Name, in.Description, in.HomepageURL, in.LogoURL, in.MinLevel,
		in.RedirectURIs, in.Scopes, in.Status, now, id)
	if err != nil {
		return nil, err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return nil, ErrNotFound
	}
	return r.FindByID(id)
}

// RotateSecret stores a new bcrypt hash. The plaintext was generated by
// the handler and is shown to the admin once; we never see it again.
func (r *OAuthClientRepo) RotateSecret(id, newHash string) error {
	now := time.Now().UTC().Format(time.RFC3339)
	res, err := r.db.Exec(
		`UPDATE oauth_clients SET client_secret_hash = ?, updated_at = ? WHERE id = ?`,
		newHash, now, id,
	)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

func (r *OAuthClientRepo) Delete(id string) error {
	res, err := r.db.Exec(`DELETE FROM oauth_clients WHERE id = ?`, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// ─── Authorization codes ─────────────────────────────────────────────────

type OAuthCode struct {
	ID                  string
	Code                string
	ClientID            string
	UserID              string
	RedirectURI         string
	Scope               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           string
	Used                bool
	CreatedAt           string
}

type OAuthCodeRepo struct{ db *sql.DB }

func NewOAuthCodeRepo(db *sql.DB) *OAuthCodeRepo { return &OAuthCodeRepo{db: db} }

type OAuthCodeInput struct {
	Code                string
	ClientID            string
	UserID              string
	RedirectURI         string
	Scope               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           time.Time
}

func (r *OAuthCodeRepo) Create(in OAuthCodeInput) (*OAuthCode, error) {
	id := uuid.NewString()
	now := time.Now().UTC().Format(time.RFC3339)
	if in.Scope == "" {
		in.Scope = "openid"
	}
	if in.CodeChallengeMethod == "" {
		in.CodeChallengeMethod = "plain"
	}
	_, err := r.db.Exec(`
		INSERT INTO oauth_codes (id, code, client_id, user_id, redirect_uri,
		    scope, code_challenge, code_challenge_method, expires_at, used,
		    created_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?)`,
		id, in.Code, in.ClientID, in.UserID, in.RedirectURI, in.Scope,
		in.CodeChallenge, in.CodeChallengeMethod,
		in.ExpiresAt.UTC().Format(time.RFC3339), now)
	if err != nil {
		return nil, err
	}
	return r.FindByCode(in.Code)
}

func (r *OAuthCodeRepo) FindByCode(code string) (*OAuthCode, error) {
	row := r.db.QueryRow(`
		SELECT id, code, client_id, user_id, redirect_uri, scope,
		       code_challenge, code_challenge_method, expires_at, used, created_at
		FROM oauth_codes WHERE code = ?`, code)
	var c OAuthCode
	var used int
	if err := row.Scan(&c.ID, &c.Code, &c.ClientID, &c.UserID, &c.RedirectURI,
		&c.Scope, &c.CodeChallenge, &c.CodeChallengeMethod, &c.ExpiresAt,
		&used, &c.CreatedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	c.Used = used == 1
	return &c, nil
}

// MarkUsed flips the used flag — call inside the same handler that swapped
// the code for a token. Must run BEFORE issuing the access token so that
// the reuse-detection logic in /token works.
func (r *OAuthCodeRepo) MarkUsed(id string) error {
	_, err := r.db.Exec(`UPDATE oauth_codes SET used = 1 WHERE id = ?`, id)
	return err
}

func (r *OAuthCodeRepo) PruneExpired() (int64, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	res, err := r.db.Exec(
		`DELETE FROM oauth_codes WHERE used = 1 OR expires_at < ?`, now)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// ─── Access + refresh tokens ─────────────────────────────────────────────

type OAuthToken struct {
	ID                     string
	AccessToken            string
	RefreshToken           string
	ClientID               string
	UserID                 string
	Scope                  string
	ExpiresAt              string
	RefreshTokenExpiresAt  string
	ParentTokenID          string
	Replaced               bool
	Revoked                bool
	RevokedAt              string
	CreatedAt              string
}

type OAuthTokenRepo struct{ db *sql.DB }

func NewOAuthTokenRepo(db *sql.DB) *OAuthTokenRepo { return &OAuthTokenRepo{db: db} }

type OAuthTokenInput struct {
	AccessToken           string
	RefreshToken          string
	ClientID              string
	UserID                string
	Scope                 string
	ExpiresAt             time.Time
	RefreshTokenExpiresAt time.Time
	ParentTokenID         string
}

func (r *OAuthTokenRepo) Create(in OAuthTokenInput) (*OAuthToken, error) {
	id := uuid.NewString()
	now := time.Now().UTC().Format(time.RFC3339)
	var refresh sql.NullString
	if in.RefreshToken != "" {
		refresh = sql.NullString{String: in.RefreshToken, Valid: true}
	}
	var refreshExpiry sql.NullString
	if !in.RefreshTokenExpiresAt.IsZero() {
		refreshExpiry = sql.NullString{
			String: in.RefreshTokenExpiresAt.UTC().Format(time.RFC3339),
			Valid:  true,
		}
	}
	var parent sql.NullString
	if in.ParentTokenID != "" {
		parent = sql.NullString{String: in.ParentTokenID, Valid: true}
	}
	_, err := r.db.Exec(`
		INSERT INTO oauth_tokens (id, access_token, refresh_token, client_id,
		    user_id, scope, expires_at, refresh_token_expires_at,
		    parent_token_id, replaced, revoked, created_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, 0, ?)`,
		id, in.AccessToken, refresh, in.ClientID, in.UserID, in.Scope,
		in.ExpiresAt.UTC().Format(time.RFC3339), refreshExpiry, parent, now)
	if err != nil {
		return nil, err
	}
	return r.FindByAccessToken(in.AccessToken)
}

const oauthTokenCols = `id, access_token, COALESCE(refresh_token, ''), client_id, user_id,
                        scope, expires_at, COALESCE(refresh_token_expires_at, ''),
                        COALESCE(parent_token_id, ''), replaced, revoked,
                        COALESCE(revoked_at, ''), created_at`

func scanOAuthToken(row interface{ Scan(dest ...any) error }) (*OAuthToken, error) {
	var t OAuthToken
	var replaced, revoked int
	if err := row.Scan(&t.ID, &t.AccessToken, &t.RefreshToken, &t.ClientID,
		&t.UserID, &t.Scope, &t.ExpiresAt, &t.RefreshTokenExpiresAt,
		&t.ParentTokenID, &replaced, &revoked, &t.RevokedAt, &t.CreatedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	t.Replaced = replaced == 1
	t.Revoked = revoked == 1
	return &t, nil
}

func (r *OAuthTokenRepo) FindByAccessToken(token string) (*OAuthToken, error) {
	row := r.db.QueryRow(`SELECT `+oauthTokenCols+` FROM oauth_tokens WHERE access_token = ?`, token)
	return scanOAuthToken(row)
}

func (r *OAuthTokenRepo) FindByRefreshToken(token string) (*OAuthToken, error) {
	row := r.db.QueryRow(`SELECT `+oauthTokenCols+` FROM oauth_tokens WHERE refresh_token = ?`, token)
	return scanOAuthToken(row)
}

// MarkReplaced flips replaced=1 when this token's refresh has been used to
// mint a new chain link. The old access_token is still valid until its
// natural expiry; only the refresh becomes single-use.
func (r *OAuthTokenRepo) MarkReplaced(id string) error {
	_, err := r.db.Exec(`UPDATE oauth_tokens SET replaced = 1 WHERE id = ?`, id)
	return err
}

// Revoke marks a single token revoked. Used by /revoke and as part of
// the chain-revoke routine below.
func (r *OAuthTokenRepo) Revoke(id string) error {
	now := time.Now().UTC().Format(time.RFC3339)
	_, err := r.db.Exec(
		`UPDATE oauth_tokens SET revoked = 1, revoked_at = ? WHERE id = ?`,
		now, id,
	)
	return err
}

// RevokeChain walks parent_token_id links from the given token both
// directions (parents and children) and revokes the entire chain. Called
// when a refresh-token reuse is detected. Returns the number of tokens
// revoked.
//
// We do this in three passes for clarity:
//  1. Walk up via parent_token_id to find the root.
//  2. Walk down: BFS through every token whose parent_token_id is in the
//     visited set.
//  3. UPDATE all visited IDs to revoked=1.
func (r *OAuthTokenRepo) RevokeChain(startID string) (int, error) {
	visited := map[string]bool{startID: true}

	// Walk up.
	current := startID
	for {
		var parent sql.NullString
		err := r.db.QueryRow(
			`SELECT parent_token_id FROM oauth_tokens WHERE id = ?`, current,
		).Scan(&parent)
		if err != nil || !parent.Valid || parent.String == "" || visited[parent.String] {
			break
		}
		visited[parent.String] = true
		current = parent.String
	}

	// BFS down.
	queue := make([]string, 0, len(visited))
	for id := range visited {
		queue = append(queue, id)
	}
	for len(queue) > 0 {
		// Build IN clause; visited is small (chain depth 1-10 typically).
		head := queue[0]
		queue = queue[1:]
		rows, err := r.db.Query(
			`SELECT id FROM oauth_tokens WHERE parent_token_id = ?`, head,
		)
		if err != nil {
			return 0, err
		}
		var children []string
		for rows.Next() {
			var id string
			if err := rows.Scan(&id); err != nil {
				rows.Close()
				return 0, err
			}
			if !visited[id] {
				visited[id] = true
				children = append(children, id)
			}
		}
		rows.Close()
		queue = append(queue, children...)
	}

	// Bulk revoke. We could batch into one UPDATE but the chain is small
	// and a loop keeps the SQL simple.
	now := time.Now().UTC().Format(time.RFC3339)
	for id := range visited {
		if _, err := r.db.Exec(
			`UPDATE oauth_tokens SET revoked = 1, revoked_at = ? WHERE id = ?`,
			now, id,
		); err != nil {
			return 0, err
		}
	}
	return len(visited), nil
}

// RevokeByUserClient revokes every token for one (user, client) pair.
// Used when a user revokes a grant from /api/account/oauth-grants.
func (r *OAuthTokenRepo) RevokeByUserClient(userID, clientID string) (int64, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	res, err := r.db.Exec(
		`UPDATE oauth_tokens SET revoked = 1, revoked_at = ?
		 WHERE user_id = ? AND client_id = ? AND revoked = 0`,
		now, userID, clientID,
	)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

func (r *OAuthTokenRepo) PruneExpired() (int64, error) {
	now := time.Now().UTC().Format(time.RFC3339)
	res, err := r.db.Exec(`
		DELETE FROM oauth_tokens
		WHERE (revoked = 1 AND revoked_at < ?)
		   OR (replaced = 1 AND created_at < ?)
		   OR (expires_at < ? AND COALESCE(refresh_token_expires_at, '') < ?)`,
		// Keep revoked rows for 7 days so audits can inspect them.
		time.Now().Add(-7*24*time.Hour).UTC().Format(time.RFC3339),
		time.Now().Add(-7*24*time.Hour).UTC().Format(time.RFC3339),
		now, now)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// ─── Grants (user ↔ client consent) ──────────────────────────────────────

type OAuthGrant struct {
	ID         string `json:"id"`
	UserID     string `json:"userId"`
	ClientID   string `json:"clientId"`
	ClientName string `json:"clientName"`
	Scopes     string `json:"scopes"` // JSON array
	Revoked    bool   `json:"revoked"`
	RevokedAt  string `json:"revokedAt,omitempty"`
	GrantedAt  string `json:"grantedAt"`
	LastUsedAt string `json:"lastUsedAt,omitempty"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type OAuthGrantRepo struct{ db *sql.DB }

func NewOAuthGrantRepo(db *sql.DB) *OAuthGrantRepo { return &OAuthGrantRepo{db: db} }

// Upsert creates the (user, client) grant if missing, or refreshes
// last_used_at + scopes on an existing one. The unique index on
// (user_id, client_id) makes this safe even under concurrent /authorize
// callbacks.
func (r *OAuthGrantRepo) Upsert(userID, clientID, clientName, scopesJSON string) error {
	now := time.Now().UTC().Format(time.RFC3339)
	id := uuid.NewString()
	_, err := r.db.Exec(`
		INSERT INTO oauth_grants (id, user_id, client_id, client_name, scopes,
		    revoked, granted_at, last_used_at, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?, ?)
		ON CONFLICT(user_id, client_id) DO UPDATE SET
		    client_name = excluded.client_name,
		    scopes = excluded.scopes,
		    revoked = 0,
		    revoked_at = NULL,
		    last_used_at = excluded.last_used_at,
		    updated_at = excluded.updated_at`,
		id, userID, clientID, clientName, scopesJSON, now, now, now, now)
	return err
}

func (r *OAuthGrantRepo) FindByUserClient(userID, clientID string) (*OAuthGrant, error) {
	row := r.db.QueryRow(`
		SELECT id, user_id, client_id, client_name, scopes, revoked,
		       COALESCE(revoked_at, ''), granted_at, COALESCE(last_used_at, ''),
		       created_at, updated_at
		FROM oauth_grants WHERE user_id = ? AND client_id = ?`, userID, clientID)
	var g OAuthGrant
	var revoked int
	if err := row.Scan(&g.ID, &g.UserID, &g.ClientID, &g.ClientName, &g.Scopes,
		&revoked, &g.RevokedAt, &g.GrantedAt, &g.LastUsedAt,
		&g.CreatedAt, &g.UpdatedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	g.Revoked = revoked == 1
	return &g, nil
}

func (r *OAuthGrantRepo) ListByUser(userID string) ([]OAuthGrant, error) {
	rows, err := r.db.Query(`
		SELECT id, user_id, client_id, client_name, scopes, revoked,
		       COALESCE(revoked_at, ''), granted_at, COALESCE(last_used_at, ''),
		       created_at, updated_at
		FROM oauth_grants WHERE user_id = ? AND revoked = 0
		ORDER BY last_used_at DESC, granted_at DESC`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []OAuthGrant
	for rows.Next() {
		var g OAuthGrant
		var revoked int
		if err := rows.Scan(&g.ID, &g.UserID, &g.ClientID, &g.ClientName,
			&g.Scopes, &revoked, &g.RevokedAt, &g.GrantedAt, &g.LastUsedAt,
			&g.CreatedAt, &g.UpdatedAt); err != nil {
			return nil, err
		}
		g.Revoked = revoked == 1
		out = append(out, g)
	}
	return out, rows.Err()
}

// Revoke marks a single grant revoked. Token revocation is the caller's
// job (via OAuthTokenRepo.RevokeByUserClient) — splitting the calls keeps
// the model layer composable.
func (r *OAuthGrantRepo) Revoke(id string) error {
	now := time.Now().UTC().Format(time.RFC3339)
	res, err := r.db.Exec(
		`UPDATE oauth_grants SET revoked = 1, revoked_at = ?, updated_at = ? WHERE id = ?`,
		now, now, id,
	)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

func (r *OAuthGrantRepo) UpdateLastUsed(userID, clientID string) error {
	now := time.Now().UTC().Format(time.RFC3339)
	_, err := r.db.Exec(
		`UPDATE oauth_grants SET last_used_at = ?, updated_at = ?
		 WHERE user_id = ? AND client_id = ?`,
		now, now, userID, clientID,
	)
	return err
}

// ─── helpers ──────────────────────────────────────────────────────────────

// ScopesIntersect returns the requested scopes that are also in allowed.
// Both args are JSON arrays of strings — we do the parsing manually here
// to avoid pulling encoding/json into a hot path; format is constrained
// to ["a","b"] so a tiny scanner suffices.
func ScopesIntersect(requested, allowed []string) []string {
	allow := make(map[string]bool, len(allowed))
	for _, s := range allowed {
		allow[s] = true
	}
	out := make([]string, 0, len(requested))
	seen := make(map[string]bool, len(requested))
	for _, s := range requested {
		s = strings.TrimSpace(s)
		if s == "" || seen[s] || !allow[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}
